image:
  repository: 178502900821.dkr.ecr.ap-south-1.amazonaws.com/devops-akki
<<<<<<< HEAD
  tag: e3c3e003716fc9c92c5174df3b92cdf114d44327

env:
  ENV: "prod"
=======
  tag: e3c3e003716fc9c92c5174df3b92cdf114d44327
>>>>>>> 89e20e246cb6c3edee129fd36e74d7898ce3a628
