apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-akki.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "devops-akki.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "devops-akki.name" . }}
      annotations:
        redeploy-timestamp: "{{ .Values.redeployTimestamp }}"

    spec:
      serviceAccountName: practice-sa
      containers:
        - name: devops-akki
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3001
          env:
            - name: APP_VERSION
              value: "{{ .Values.env.APP_VERSION }}"
            - name: ENV
              value: "{{ .Values.env.ENV }}"
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
